modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="MIT"

[[mods]]
modId="clockwork_rails"
version="${version}"
displayName="Clockwork Rail"
description='''
Control minecart rail junctions using Create-inspired rotation, and power minecarts using stored Stress from Create.
'''
authors="Chadd Klaus (@Sempiternity)"

[[dependencies.clockwork_rails]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.clockwork_rails]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
